### PR TITLE
Feature/fix sso edit access

### PR DESCRIPTION
**Pull request by flibbertigibbet**
* Fix JS error on login page
* Set write access cookie on SSO login
* Workaround for [this issue](https://github.com/rohe/pyoidc/issues/161)

### CODE REVIEW

**Comment by flibbertigibbet** [comment]
Tested locally.

**Comment by kshepard** [comment]
:+1:

**Comment by ddohler** [comment]
Ugh, sorry, I reviewed this yesterday but forgot to actually write the +1; looks good to me too.

**Comment by flibbertigibbet** [comment]
Thanks!

**Pull request merged**
