### PR TITLE
Feature/namespace configs

### LINKED ISSUE #83: Schema editor config.js overrides web app config.js
Modifying the web app `config.js` template has no effect without making a matching edit to the schema editor `config.js`. On provisioning, the web app `config.js` template file does get copied to the correct directory (`/opt/web/`) and is correct in the web docker container.

Apparently both `config.js`files load on a request to the web app, the editor config loading second.

### PR DESCRIPTION
**Pull request by flibbertigibbet**
Closes #83.

Namespace the two `Config` Angular constant objects loaded by the web app (which also loads the schema editor's resources).

### CODE REVIEW

**Comment by ddohler** [comment]
Why are Schema Editor resources getting loaded in the web app in the first place? My initial thought is that that would itself be something we should fix, but there might be a reason the web app needs them.

**Comment by flibbertigibbet** [comment]
The editor is a dependency of the web app. There's several places where editor things are imported and referenced, including in tests, so the relationship seems very intentional. I don't know why the decision was made to do things that way.

**Comment by moradology** [comment]
Ditto on what @flibbertigibbet said. It makes sense as things are now and I am unclear on why they are this way.

**Comment by moradology** [comment]
+1

**Pull request merged**
