### PR TITLE
Add config mock

### PR DESCRIPTION
**Pull request by kshepard**
This should fix the Travis failures.

### CODE REVIEW

**Comment by CloudNiner** [comment]
And this doesn't explode if config.js already exists elsewhere?

**Comment by CloudNiner** [comment]
Also might be worth a comment in the ansible config.js template to remind devs to update this file as well when they add a key in the ansible template.

**Comment by CloudNiner** [comment]
+1 on travis

**Comment by kshepard** [comment]
Doesn't seem to explode with a config.js in place. Good idea on the ansible template note, I'll add it.

**Pull request merged**
