### PR TITLE
Feature/region saving2

### PR DESCRIPTION
**Pull request by fungjj92**
Persist region across app

We want to save boundary data between sessions. So I changed localStorageService to local instead of session storage. Previously sessionStorage was chosen -- was this for a particular reason that this change shouldn't quash?
PR #142 

Oddity/bug under investigation: Local storage only works if browser history is cleared.

### CODE REVIEW

**Comment by flibbertigibbet** [comment]
My understanding was that the issue was boundary selection used to persist, but has broken recently. Is this to address a different issue?

**Comment by fungjj92** [comment]
Two things:
- The blackspot map didn't adhere to the set boundary when changed outside the dashboard page
- Boundary selection persists, but not forever. John logged out, waited ~1 hr, and boundaries were lost upon login.

**Comment by flibbertigibbet** [comment]
Ah, ok. Thanks for clearing that up.

**Comment by flibbertigibbet** [comment]
:+1:

**Pull request merged**
