### PR TITLE
Feature/widget editing

### PR DESCRIPTION
**Pull request by fungjj92**
Replace recent-proportions widget with the saved filters
Some styling changes that would like feedback @mtedeschi 
**Before**
screen shot 2016-04-12 at 3 28 13 pm

**Afters**
screen shot 2016-04-12 at 3 22 35 pm
screen shot 2016-04-12 at 3 22 18 pm

### CODE REVIEW

**Comment by kshepard** [comment]
Might be worth looking at this first (and possibly merging it in) to make sure they can peacefully coexist: https://github.com/WorldBank-Transport/DRIVER/pull/480

**Comment by jbranigan** [comment]
@mtedeschi Could you take a look at this? We decided to remove one of the widgets because of its complexity, but are now unsure of the layout. Thanks!

**Comment by jbranigan** [comment]
@mtedeschi Bumping this - would be great to merge soon

**Comment by kshepard** [comment]
Closing this PR as we've decided to go a different route with removing this widget (it will either be transformed to a new widget, or another widget will be split out to take up its real estate).

**Pull request closed without merging**
