### PR TITLE
Add --authz param to load_accidents_v3.py

### PR DESCRIPTION
**Pull request by sharph**

### CODE REVIEW

**Comment by kshepard** [comment]
+1. Would you be able to update the "Testing Data" section of the readme to mention that a token should be obtained and what the string being passed into the authz arg should look like?

**Comment by sharph** [comment]
Sure

**Comment by kshepard** [comment]
Just a reminder: noticed this is still active.

**Comment by sharph** [comment]
Yep, I haven't forgotten. It's just been low on my list. Finally getting to it now.

**Comment by sharph** [comment]
Instructions added

**Comment by kshepard** [comment]
Cool, +1

**Pull request merged**
