### PR TITLE
Tabbed details view

### PR DESCRIPTION
**Pull request by kshepard**
Will add remaining tests for controllers/directives before merging.

### CODE REVIEW

**Comment by moradology** [comment]
Looks like this is maybe a good idea for the textarea `<pre>` elements: https://css-tricks.com/snippets/css/make-pre-text-wrap/

**Comment by moradology** [comment]
This looks really good; +1 after trying to get that text to wrap

**Comment by kshepard** [comment]
Cool, good call on the text wrap. Didn't have any text long enough in my tests to notice it didn't wrap.

**Comment by moradology** [comment]
Yeah, and `pre` is a really obscure tag

**Pull request merged**
