### PR TITLE
Don't place marker on double-click

### PR DESCRIPTION
**Pull request by ddohler**
Delays placing a marker in order to wait for a double click. If a double
click happens, the marker is not placed.

### CODE REVIEW

**Comment by flibbertigibbet** [comment]
+1

I suppose there wouldn't be any additional benefit to using [Rick's library](https://github.com/azavea/Leaflet.favorDoubleClick)?

**Comment by ddohler** [comment]
I talked to Rick and he said that his library only works on limited versions of Leaflet and he hasn't had a chance to update it.

**Comment by flibbertigibbet** [comment]
Ok, good to know.

**Comment by ddohler** [comment]
Had to rework one of the tests after this change, and I added another one for good measure.

**Pull request merged**
