### PR TITLE
Fix latlng position and precision

### PR DESCRIPTION
**Pull request by fungjj92**
Round lat long on driver record views to 5 decimal places (< 1 m error) and move under map

### CODE REVIEW

**Comment by kshepard** [comment]
This looks good, but the change also needs to be made on the add/edit page (add-edit-partial.html).

**Comment by fungjj92** [comment]
Heard & done!

**Comment by fungjj92** [comment]
Heard & done!

**Comment by kshepard** [comment]
+1, nice. I'll merge this since you're not a member of the org yet.

**Pull request merged**
