### PR TITLE
Feature/map updates

### PR DESCRIPTION
**Pull request by flibbertigibbet**
* Refactor map layer directive logic into controller
* Add styling for events and boundaries layers
* Add event interactivity to the layer switcher
* Only show events and interactivity by default

Will add some tests.

### CODE REVIEW

**Comment by flibbertigibbet** [comment]
Events + boundaries:
image

Heatmap shows on top of events now that layer zIndex is set explicitly.

**Comment by kshepard** [comment]
+1, nice refactor.

**Comment by jbranigan** [comment]
Yay

**Comment by flibbertigibbet** [comment]
Can't get tests to run for the layers controller, seems to be related to UTFGrid. Merging.

**Pull request merged**
