### PR TITLE
Move details section to top of editor form

### PR DESCRIPTION
**Pull request by flibbertigibbet**

### CODE REVIEW

**Comment by flibbertigibbet** [comment]
Tests pass locally. Not sure what's going on with the failures here.

**Comment by ddohler** [comment]
Have you looked into inserting the `propertyOrder` keyword into the Details property in the record schema? I think it would probably need to happen here: https://github.com/WorldBank-Transport/DRIVER/blob/develop/schema_editor/app/scripts/views/recordtype/add-controller.js#L47

**Comment by flibbertigibbet** [comment]
Not being part of what current `json-editor` structure expects, would it respect it?

**Comment by ddohler** [comment]
It may; `propertyOrder` is a custom keyword [defined by json-editor](https://github.com/jdorn/json-editor#property-ordering) so it will hopefully work although json-editor can sometimes be fiddly about such things.

**Comment by flibbertigibbet** [comment]
It only gets added to the subsections, not the parent sections at the level of `Details`; none of the other sections have `propertyOrder` defined.

**Comment by flibbertigibbet** [comment]
Yay, the editor does respect `propertyOrder` on the parent items, even though it doesn't write anything for that property. It must use the default value of 1000 internally only.

**Comment by ddohler** [comment]
+1

**Comment by flibbertigibbet** [comment]
@kshepard I expect we will need the data loader to set `propertyOrder` on the `Details` section when it creates the schema as well; you might want to put that into the new data loader.

**Comment by kshepard** [comment]
Good call, I will do so.

**Comment by kshepard** [comment]
Interestingly the propertyOrder doesn't seem to work its magic on the other properties. I have Accident Details, Person, and Vehicle, and no matter what, I can't get Vehicle to come before Person.

**Comment by flibbertigibbet** [comment]
Well, @jbranigan says he's only interested in pushing Details to the top at the moment. Good to know, though.

**Comment by kshepard** [comment]
Yeah, it's going to be annoying for data input though, since Person has a reference to Vehicle, so vehicles need to be entered first.

**Comment by flibbertigibbet** [comment]
Ah, good point.

**Pull request merged**
